# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeenThereDoneThat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Firebase/Core'
	pod 'GoogleSignIn'
	pod 'Firebase/Auth'
  # Pods for BeenThereDoneThat

  target 'BeenThereDoneThatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BeenThereDoneThatUITests' do
    # Pods for testing
  end

end
